/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 주문 상품 정보 : 대표 이미지, 상품명, 모델명, 개당 가격
 */
export interface CartProductDTO {
  /** 장바구니 id */
  cartId?: number;
  /** 상품 id */
  productId?: number;
  /** 상품 대표이미지 */
  coverImage?: string;
  /** 상품명 */
  productName?: string;
  /** 모델명 */
  productModel?: string;
  /** 선택한 옵션 */
  selectOption?: string;
  /** 기재한 옵션 */
  inputOption?: string;
  /** 상품 개별 금액 */
  productPrice?: number;
  /** 주문 수량 */
  quantity?: number;
  /** 수량 * 상품 가격 */
  totalPrice?: number;
}
