/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';
import type { CartCartStatus } from './cartCartStatus';
import type { Product } from './product';

export interface Cart {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  user?: User;
  quantity?: number;
  selectOption?: string;
  inputOption?: string;
  price?: number;
  totalPrice?: number;
  cartStatus?: CartCartStatus;
  product?: Product;
}
