/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface CartRequestDTO {
  /** 선택한 상품 옵션 */
  selectOption?: string;
  /** 기재한 옵션 */
  inputOption?: string;
  /** 상품 수량 */
  quantity?: number;
}
