/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type CartCartStatus = (typeof CartCartStatus)[keyof typeof CartCartStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartCartStatus = {
  IN_CART: 'IN_CART',
  ORDERED: 'ORDERED',
} as const;
