/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CartResponseDTOProductCategory } from './cartResponseDTOProductCategory';

/**
 * 상품 List : 상품 대표 이미지 , 상품명, 모델명, 수량, 결제 금액
 */
export interface CartResponseDTO {
  /** 장바구니 id */
  id?: number;
  /** 상품 대표이미지 */
  coverImage?: string;
  /** 상품 카테고리 */
  productCategory?: CartResponseDTOProductCategory;
  /** 상품명 */
  productName?: string;
  /** 모델명 */
  productModel?: string;
  /** 선택한 옵션 */
  selectOption?: string;
  /** 기재한 옵션 */
  inputOption?: string;
  /** 상품 금액 */
  productPrice?: number;
  /** 주문 수량 */
  quantity?: number;
  /** 상품 전체 옵션 */
  productOptions?: string[];
}
