/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface Company {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  user?: User;
  managerName?: string;
  managerPhone?: string;
  companyName?: string;
  companyNumber?: string;
  companyType?: string;
  companyItem?: string;
  companyDescription?: string;
}
