/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CompanyDetailDTORole } from './companyDetailDTORole';

/**
 * 응답 데이터
 */
export interface CompanyDetailDTO {
  /** 회원 id */
  id?: number;
  /** 단가 적용 */
  role?: CompanyDetailDTORole;
  /** 회원 아이디 */
  userid?: string;
  /** 회원 이름 */
  username?: string;
  /** 전화번호 */
  phone?: string;
  /** email */
  email?: string;
  /** 주소 */
  address?: string;
  /** 상세 주소 */
  addressDetail?: string;
  /** 우편 번호 */
  zipCode?: string;
  /** 포인트 */
  point?: number;
  /** 담당자 이름 */
  managerName?: string;
  /** 담당자 연락처 */
  managerPhone?: string;
  /** 상호 */
  companyName?: string;
  /** 사업자 번호 */
  companyNumber?: string;
  /** 업태 */
  companyType?: string;
  /** 종목 */
  companyItem?: string;
  /** 기타 문구 기재 */
  companyDescription?: string;
}
