/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 단가 적용
 */
export type CompanyDetailDTORole = (typeof CompanyDetailDTORole)[keyof typeof CompanyDetailDTORole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyDetailDTORole = {
  MEMBER: 'MEMBER',
  DEALER: 'DEALER',
  BEST: 'BEST',
  BUSINESS: 'BUSINESS',
  ADMIN: 'ADMIN',
} as const;
