/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { SignUpUserInfoDto } from './signUpUserInfoDto';
import type { Company } from './company';

/**
 * 공급업체 회원가입
 */
export interface CompanySignUpDTO {
  signUpUserInfoDto?: SignUpUserInfoDto;
  company?: Company;
}
