/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface DeliveryAddress {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  name?: string;
  recipientName?: string;
  phoneNumber?: string;
  address?: string;
  addressDetail?: string;
  zipcode?: string;
  user?: User;
}
