/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 배송지 목록
 */
export interface DeliveryAddressDetailDTO {
  /** 배송지 id */
  deliveryAddressId?: number;
  /** 배송지 별명 */
  name?: string;
  /** 수령인 이름 */
  recipientName?: string;
  /** 수령인 연락처 */
  phoneNumber?: string;
  /** 배송지 주소 */
  address?: string;
  /** 배송지 상세 주소 */
  addressDetail?: string;
  /** 배송지 우편 번호 */
  zipcode?: string;
  /** 기본 배송지 설정 여부 */
  isDefault?: boolean;
}
