/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type GetNoticeDetail401 = {
  /** 에러 코드 */
  code?: number;
  /** 에러 메시지 */
  message?: string;
};
