/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type GetPresignedUrlParams = {
  /**
   * 이미지 저장 시 prefix
   */
  prefix: string;
  /**
   * 파일명
   */
  fileName?: string;
};
