/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductsCategory } from './getProductsCategory';

export type GetProductsParams = {
  category: GetProductsCategory;
  page: number;
  size: number;
};
