/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersFilteredBy } from './getUsersFilteredBy';

export type GetUsersParams = {
/**
 * 단가 적용 필터링
 */
filteredBy?: GetUsersFilteredBy;
page: number;
size: number;
};
