/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { HitDTO } from './hitDTO';

/**
 * 응답 데이터
 */
export interface HitListDTO {
  /** hitList */
  hits?: HitDTO[];
  /** 평균 */
  averageHit?: number;
  /** 총 계 */
  totalHit?: number;
  /** 누적 총 계 */
  overAllTotalHit?: number;
}
