/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * user 등급
 */
export type LoginDtoUserRole = typeof LoginDtoUserRole[keyof typeof LoginDtoUserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginDtoUserRole = {
  MEMBER: 'MEMBER',
  DEALER: 'DEALER',
  BEST: 'BEST',
  BUSINESS: 'BUSINESS',
  ADMIN: 'ADMIN',
} as const;
