/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LoginDtoUserRole } from './loginDtoUserRole';

/**
 * 응답 데이터
 */
export interface LoginDto {
  /** user 등급 */
  userRole?: LoginDtoUserRole;
  /** token 값 */
  accessToken?: string;
}
