/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface NoticeDTO {
  /** 게시글 id */
  id?: number;
  /** 게시글 제목 */
  noticeTitle?: string;
  /** 게시글 파일명 */
  noticeFileName?: string;
  /** 게시글 작성자 */
  noticeAuthor?: string;
  /** 게시글 작성일 */
  noticeCreateDate?: string;
  /** 게시글 조회수 */
  viewCount?: number;
}
