/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { NoticeFileDTO } from './noticeFileDTO';

/**
 * 응답 데이터
 */
export interface NoticeDetailDTO {
  /** 게시글 id */
  id?: number;
  /** 게시글 제목 */
  noticeTitle?: string;
  /** 게시글 내용 */
  noticeContent?: string;
  /** 게시글 파일 */
  noticeFiles?: NoticeFileDTO[];
  /** 게시글 작성자 */
  noticeAuthor?: string;
  /** 게시글 작성일 */
  noticeCreateDate?: string;
  /** 게시글 조회수 */
  viewCount?: number;
  /** 게시글 팝업 설정 여부 */
  isPop?: boolean;
}
