/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { Notice } from './notice';

export interface NoticeFile {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  fileName?: string;
  fileUrl?: string;
  notice?: Notice;
}
