/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 게시글 파일
 */
export interface NoticeFileDTO {
  /** 게시글 파일 id */
  id?: number;
  /** 게시글 파일명 */
  fileName?: string;
  /** 게시글 파일 URL */
  fileUrl?: string;
}
