/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderDetailResponseDTOOrderStatus } from './orderDetailResponseDTOOrderStatus';
import type { CartProductDTO } from './cartProductDTO';
import type { UserOrderDetailDTO } from './userOrderDetailDTO';
import type { DeliveryAddressDetailDTO } from './deliveryAddressDetailDTO';
import type { OrderDetailResponseDTOPaymentMethod } from './orderDetailResponseDTOPaymentMethod';

/**
 * 응답 데이터
 */
export interface OrderDetailResponseDTO {
  /** 주문 ID */
  orderId?: number;
  /** 주문 일자 */
  orderDate?: string;
  /** 주문 번호 */
  imp_uid?: string;
  /** 주문 상태를 나타내는 열거형 */
  orderStatus?: OrderDetailResponseDTOOrderStatus;
  /** 주문 요청 사항 */
  request?: string;
  /** 주문 상품 List */
  products?: CartProductDTO[];
  user?: UserOrderDetailDTO;
  deliveryAddress?: DeliveryAddressDetailDTO;
  /** 주문 금액 */
  price?: number;
  /** 할인 금액 */
  discountPrice?: number;
  /** 배송비 */
  shippingCost?: number;
  /** 실제로 결제한 금액 */
  totalPrice?: number;
  /** 결제 수단 */
  paymentMethod?: OrderDetailResponseDTOPaymentMethod;
  /** 매출전표 URL */
  receipt_url?: string;
  /** 현금 영수증 URL */
  cash_receipt_url?: string;
}
