/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 주문 상태를 나타내는 열거형
 */
export type OrderDetailResponseDTOOrderStatus = typeof OrderDetailResponseDTOOrderStatus[keyof typeof OrderDetailResponseDTOOrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDetailResponseDTOOrderStatus = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  SHIPPING: 'SHIPPING',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',
} as const;
