/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderOrderStatus } from './orderOrderStatus';
import type { OrderPaymentMethod } from './orderPaymentMethod';
import type { OrderPaymentStatus } from './orderPaymentStatus';
import type { Cart } from './cart';
import type { User } from './user';
import type { DeliveryAddress } from './deliveryAddress';

export interface Order {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  orderNumber?: string;
  /** 주문 상태를 나타내는 열거형 */
  orderStatus?: OrderOrderStatus;
  paymentMethod?: OrderPaymentMethod;
  paymentStatus?: OrderPaymentStatus;
  pointsToUse?: number;
  pointsToEarn?: number;
  amount?: number;
  shippingCost?: number;
  receiptUrl?: string;
  cashReceiptUrl?: string;
  request?: string;
  carts?: Cart[];
  user?: User;
  deliveryAddress?: DeliveryAddress;
}
