/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 결제 상태
 */
export type OrderDetailDTOPaymentStatus = typeof OrderDetailDTOPaymentStatus[keyof typeof OrderDetailDTOPaymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDetailDTOPaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;
