/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryAddress } from './deliveryAddress';
import type { OrderRequestDTOPaymentMethod } from './orderRequestDTOPaymentMethod';

export interface OrderRequestDTO {
  deliveryAddress?: DeliveryAddress;
  /** 요청 사항 */
  request?: string;
  /** 배송비 */
  shoppingCost?: number;
  /** 사용할 적립금 */
  pointsToUse?: number;
  /** 적립될 적립금 */
  pointsToEarn?: number;
  /** 결제 방법 */
  paymentMethod?: OrderRequestDTOPaymentMethod;
}
