/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 결제 수단
 */
export type OrderDetailResponseDTOPaymentMethod = typeof OrderDetailResponseDTOPaymentMethod[keyof typeof OrderDetailResponseDTOPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDetailResponseDTOPaymentMethod = {
  CREDIT_CARD: 'CREDIT_CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  V_BANK: 'V_BANK',
} as const;
