/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CartResponseDTO } from './cartResponseDTO';
import type { OrderResponseDTOPaymentMethod } from './orderResponseDTOPaymentMethod';

/**
 * 응답 데이터
 */
export interface OrderResponseDTO {
  /** 주문 id */
  id?: number;
  /** 주문 날짜 */
  createdAt?: string;
  /** 주문 번호 */
  orderNumber?: string;
  /** 상품 List : 상품 대표 이미지 , 상품명, 모델명, 수량, 결제 금액 */
  products?: CartResponseDTO[];
  /** 주문자 이름 */
  userName?: string;
  /** 주문자 연락처 */
  userPhone?: string;
  /** 결제 방법 */
  paymentMethod?: OrderResponseDTOPaymentMethod;
  /** 할인 금액(적립금 사용 금액) */
  usedPoint?: number;
  /** 배송비 */
  shippingCost?: number;
  /** 총 결제 금액 */
  totalPrice?: number;
}
