/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 상품 카테고리
 */
export type ProductDetailResponseDTOCategory =
  (typeof ProductDetailResponseDTOCategory)[keyof typeof ProductDetailResponseDTOCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductDetailResponseDTOCategory = {
  HEADSET: 'HEADSET',
  PHONE_AMP: 'PHONE_AMP',
  LINE_CORD: 'LINE_CORD',
  RECORDER: 'RECORDER',
  ACCESSORY: 'ACCESSORY',
} as const;
