/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCategory } from './productCategory';

export interface Product {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  productName?: string;
  productModel?: string;
  options?: string[];
  category?: ProductCategory;
  content?: string;
  priceBussiness?: number;
  priceBest?: number;
  priceDealer?: number;
  priceCustomer?: number;
  pictures?: string[];
  coverImage?: string;
}
