/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { ProductRequestDTOCategory } from './productRequestDTOCategory';

export interface ProductRequestDTO {
  /** 모델명 */
  productModel?: string;
  /** 상품명 */
  productName?: string;
  /** 옵션 */
  options?: string[];
  /** 상품 카테고리 */
  category?: ProductRequestDTOCategory;
  /** 상품 내용 */
  content?: string;
  /** 가격 */
  price?: string;
  /** 가격 Bussiness */
  priceBussiness?: string;
  /** 가격 Best */
  priceBest?: string;
  /** 가격 Dealer */
  priceDealer?: string;
  /** 가격 Customer */
  priceCustomer?: string;
  /** 상품 사진들 */
  pictures?: string[];
  /** 대표 이미지 */
  coverImage?: string;
}
