/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface ProductResponseDTO {
  /** 상품 id */
  id?: number;
  /** 모델명 */
  productModel?: string;
  /** 상품명 */
  productName?: string;
  /** 가격 */
  price?: string;
  /** 대표 이미지 */
  coverImage?: string;
}
