/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpRequestDto {
  /** 회원 아이디 */
  userid?: string;
  /** 닉네임 */
  username?: string;
  /** 비밀번호 */
  password?: string;
  /** 전화번호 */
  phone?: string;
  /** email */
  email?: string;
  /** 주소 */
  address?: string;
  /** 상세 주소 */
  addressDetail?: string;
  /** 우편 번호 */
  zipCode?: string;
}
