/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type SignUpUserInfoDtoRole =
  (typeof SignUpUserInfoDtoRole)[keyof typeof SignUpUserInfoDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignUpUserInfoDtoRole = {
  MEMBER: 'MEMBER',
  DEALER: 'DEALER',
  BEST: 'BEST',
  BUSINESS: 'BUSINESS',
  ADMIN: 'ADMIN',
} as const;
