/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { SignUpUserInfoDtoRole } from './signUpUserInfoDtoRole';

export interface SignUpUserInfoDto {
  userid?: string;
  username?: string;
  password?: string;
  phone?: string;
  email?: string;
  role?: SignUpUserInfoDtoRole;
  address?: string;
  addressDetail?: string;
  zipCode?: string;
}
