/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CreatedCartDTO } from './createdCartDTO';

/**
 * 성공 응답
 */
export interface SuccessResponseCreatedCartDTO {
  /** HTTP 상태 코드 */
  code?: number;
  /** 응답 메시지 */
  message?: string;
  data?: CreatedCartDTO;
}
