/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 성공 응답
 */
export interface SuccessResponseLong {
  /** HTTP 상태 코드 */
  code?: number;
  /** 응답 메시지 */
  message?: string;
  /** 응답 데이터 */
  data?: number;
}
