/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderListDTO } from './orderListDTO';

/**
 * 성공 응답
 */
export interface SuccessResponseOrderListDTO {
  /** HTTP 상태 코드 */
  code?: number;
  /** 응답 메시지 */
  message?: string;
  data?: OrderListDTO;
}
