/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { CartProductDTO } from './cartProductDTO';

/**
 * 응답 데이터
 */
export interface TemporaryOrderDTO {
  /** 주문 상품 정보 : 대표 이미지, 상품명, 모델명, 개당 가격 */
  cartProductDTOS?: CartProductDTO[];
  /** 주문자 이름 */
  userName?: string;
  /** 주문자 이메일 */
  userEmail?: string;
  /** 상품 전체 가격 */
  totalPrice?: number;
  /** 전체 적립금 */
  totalPoint?: number;
  /** 적립 예정 포인트 */
  pointToEarn?: number;
}
