/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrderStatusStatus } from './updateOrderStatusStatus';

export type UpdateOrderStatusParams = {
  /**
   * 주문 상태를 나타내는 열거형
   */
  status: UpdateOrderStatusStatus;
};
