/**
 * Generated by orval v7.11.2
 * Do not edit manually.
 * Telegro API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductRequestDTO } from './productRequestDTO';

export type UpdateProductBody = ProductRequestDTO;
