/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryAddressDetailDTO } from './deliveryAddressDetailDTO';

/**
 * 응답 데이터
 */
export interface UserInfoDTO {
  /** 회원 id */
  id?: number;
  /** 회원 이름 */
  userName?: string;
  /** 회원 아이디 */
  userId?: string;
  /** 전화번호 */
  phone?: string;
  /** 이메일 */
  email?: string;
  /** 적립금 */
  point?: number;
  /** 배송지 목록 */
  addressList?: DeliveryAddressDetailDTO[];
}
