/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 주문자 정보
 */
export interface UserOrderInfoDTO {
  id?: number;
  username?: string;
}
