/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';
import type { DeliveryAddress } from './deliveryAddress';
import type { Order } from './order';
import type { Company } from './company';

export interface User {
  createdAt?: string;
  updatedAt?: string;
  id?: number;
  username?: string;
  userId?: string;
  password?: string;
  role?: UserRole;
  phone?: string;
  email?: string;
  address?: string;
  addressDetail?: string;
  zipCode?: string;
  totalPrice?: number;
  point?: number;
  deliveryAddresses?: DeliveryAddress[];
  orders?: Order[];
  company?: Company;
}
