/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 구매자 정보
 */
export interface UserOrderDetailDTO {
  /** 주문자명(상호명) */
  name?: string;
  /** 주문자 연락처(상호 전화번호) */
  phone?: string;
  /** 담당자 연락처 */
  managerPhone?: string;
  /** 이메일 */
  email?: string;
}
