/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTORole } from './userDTORole';

export interface UserDTO {
  /** 회원 id */
  id?: number;
  /** 단가 적용 */
  role?: UserDTORole;
  /** 회원 이름 */
  userName?: string;
  /** 전화번호 */
  phone?: string;
  /** 이메일 */
  email?: string;
  /** 회원 아이디 */
  userId?: string;
  /** 가입일 */
  createdDate?: string;
  /** 총 주문액 */
  totalPrice?: number;
  /** 사용 가능한 포인트 */
  point?: number;
}
