/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Telegro API
 * Telegro API 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface WebhookDTO {
  imp_uid?: string;
  merchant_uid?: string;
  status?: string;
  cancellation_id?: string;
}
